name: 'check-permission'
description: Check user permission
inputs:
  username:
    description: 'The username to check'
    required: true
runs:
  using: composite
  steps:
    - uses: actions-cool/check-user-permission@main
      id: checkUser
      with:
        username: ${{ inputs.username }}
        check-contributor: true
        require: 'write'
    - name: Fail on workflow triggered by external contributor
      if: ${{ steps.checkUser.outputs.require-result != 'true' }}
      shell: bash
      run: |
        echo "🚫 **${{ github.actor }}** is an external contributor, only **${{ github.repository }}** team members can run workflow" \
          | tee -a $GITHUB_STEP_SUMMARY && exit 1
