name: 'run-validation'
description: 'Build and test'
inputs:
  java_version:
    description: 'Java Version'
    default: '17'
  ref:
    description: 'Ref'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
    - name: Build
      shell: bash
      run: |
        set -x -e -o pipefail
        mvn -V -e -B -ntp -DskipTests install
    - name: Test
      shell: bash
      run: |
        set -x -e -o pipefail
        mvn -V -e -B -ntp verify -DtrimStackTrace=false
    - name: Publish Unit Test Results
      if: ${{ failure() || success() }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: "**/target/*-reports/TEST*.xml"
        check_run_annotations: all tests, skipped tests
