name: Chrome setup test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited]
env:
  JAVA_VERSION: 17
jobs:
  chrome_setup_test:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
        id: setup-chrome
        with:
          chrome-version: stable
      - name: Add chrome to PATH
        run: |
          test -f /usr/bin/google-chrome && mv /usr/bin/google-chrome /usr/bin/google-chrome-ori || echo "/usr/bin/google-chrome not found"
          ln -s ${{ steps.setup-chrome.outputs.chrome-path }} /usr/bin/google-chrome
      - name: Build
        run: |
          env | sort
          which chrome || echo "chrome not found"
          which google-chrome || echo "google-chrome not found"
