name: Chromedriver test
on:
  workflow_dispatch:
    inputs:
      install:
        description: install chrome
        default: true
        type: boolean
jobs:
  setup-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
        id: setup-chrome
        if: ${{ !vars.QH_DISABLE_CHROME_INSTALL }}
        with:
          chrome-version: stable
      - name: Build
        run: |
          set -x -e -o pipefail
          mvn -V -e -B -ntp help:evaluate -Dexpression="selenide.browserBinary" -Dselenide.browserBinary=${{ steps.setup-chrome.outputs.chrome-path }}
