name: Format Pull Request
on:
  pull_request:
    types: ["labeled"]
permissions:
  pull-requests: write

jobs:
  format-pr:
    if: ${{ github.event.pull_request.merged == false && github.event.label.name == 'auto-format' }}
    runs-on: ubuntu-latest
    name: Apply format
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Apply changes
        run: |
          echo "" >> src/main/java/com/acme/example/MyClass.java
          git config --global user.email "quarkus-hilla-github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -am "chore(auto-format): apply formatting"
          git push
      - name: Add label to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const labelToAdd = 'format:applied';

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: [labelToAdd],
            });

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}