name: Snapshots Validation
on:
  workflow_dispatch:
jobs:
  snapshot_builds:
    strategy:
      matrix:
        hilla: ["2.1-SNAPSHOT", "1.3-SNAPSHOT"]
        java: [17]
        include:
          - hilla: "1.3-SNAPSHOT"
            java: 11
            branch: 1.0
          - hilla: "2.1-SNAPSHOT"
            branch: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build
        run: |
          echo "mvn clean install -Dhilla.version=${{ matrix.hilla }}"
          
