name: Nightly tasks
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Branch to update"
        required: true
        type: choice
        default: 'main'
        options:
          - main
          - "2.0"
          - "1.0"
  schedule:
    - cron: '5 * * * *'
jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Compute matrix
        id: set-matrix
        run: |
          if [[ -z "${{ inputs.target-branch }}" ]]; then
            echo 'matrix={ "branch": ["main","2.0","1.0"] }' >> "$GITHUB_OUTPUT"
          else
            echo 'matrix={ "branch": ["${{ inputs.target-branch }}"] }' >> "$GITHUB_OUTPUT"
          fi
  run-tasks:
    runs-on: ubuntu-latest
    needs: compute-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.compute-matrix.outputs.matrix)}}
    steps:
      - name: Test me
        run: |
          echo "Running for branch ${{ matrix.branch }}"
          echo "Done ${{ matrix.branch }}" >> "$GITHUB_STEP_SUMMARY"
