name: Update NPM dependencies
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Branch to update"
        required: true
        type: choice
        default: 'main'
        options:
          - main
          - "2.0"
          - "1.0"
permissions:
  pull-requests: write
  contents: write
jobs:
  update-npm-deps:
    runs-on: ubuntu-latest
    name: Update NPM dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ inputs.target-branch }}
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Search existing PR
        id: searchpr
        run: |
          existingPR=$(gh pr list --author "app/quarkus-hilla-bot" --json id,title,baseRefName,headRefName,number | \
            jq '.[] | select( .baseRefName == "${{ inputs.target-branch }}" and .headRefName == "chore/update_npm_deps_${{ inputs.target-branch }}" ) | .number')
          echo "prNumber=${existingPR:-0}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout and rebase PR
        if: ${{ steps.searchpr.prNumber != '0' }}
        run: |
          gh pr checkout ${{ steps.searchpr.prNumber }}
          git rebase ${{ inputs.target-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          set -x -e -o pipefail
          mvn -V -e -B -ntp -DskipTests install -Pproduction
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit-changes
        with:
          commit_message: "chore(npm-deps): update npm dependencies"
          commit_user_name: "quarkus-hilla-bot[bot]"
          commit_user_email: "141157179+quarkus-hilla-bot[bot]@users.noreply.github.com"
          branch: "chore/update_npm_deps_${{ inputs.target-branch }}"
          create_branch: ${{ steps.searchpr.prNumber == '0' }}
          file_pattern: ':(glob)**/package*.json'
      - name: Generate token
        uses: tibdex/github-app-token@v1
        if: ${{ steps.commit-changes.outputs.changes_detected == 'true' && steps.searchpr.prNumber == '0' }}
        id: generate-token
        with:
          app_id: ${{ secrets.QUARKUS_HILLA_BOT_ID }}
          private_key: ${{ secrets.QUARKUS_HILLA_BOT_PRIVATE_KEY }}
      - name: Create PR
        if: ${{ steps.commit-changes.outputs.changes_detected == 'true' && steps.searchpr.prNumber == '0' }}
        run: |
          gh pr create --head chore/update_npm_deps_${{ inputs.target-branch }} --base ${{ inputs.target-branch }} \
            --title "chore(npm-deps): update npm dependencies (${{ inputs.target-branch }})" \
            --label "dependencies" > out.txt 2>&1
          cat out.txt | tee -a $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
